apiVersion: apps/v1
kind: Deployment #creando un deployment
metadata:
  name: backend2 #nombre del componente
spec: #especificaciones
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: #de aqui es donde sacare la imagen para crear mis pods respecto a estas
      containers:
      - name: app2
        image: app2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80